services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-tracking
    ports:
      - "5000:5000"
    volumes:
      - ./artifacts:/mlflow/artifacts
      - ./metrics.db:/mlflow/metrics.db
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/metrics.db
      --serve-artifacts
      --artifacts-destination /mlflow/artifacts
      --default-artifact-root mlflow-artifacts:/
      --host 0.0.0.0
      --port 5000
    restart: always
